# Generated by Django 4.1.7 on 2023-03-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProjectRegistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp_name', models.CharField(max_length=30)),
                ('supp_email', models.EmailField(max_length=30)),
                ('supp_phonenumber', models.IntegerField(max_length=15)),
            ],
        ),
    ]
